### ISSUE TITLE
NSwag autogenerated code throws exception when creating.

### ISSUE THREAD

**Issue by elcondedebahia** [JasonGT/NorthwindTraders#25]
When you create a new item, the NSwag code expects for a response code 200 or 204, if not it throws and exception. The creation command returns a 201 code.
This issue cause that you can't susbscribe to call to the create command.

**Comment by JasonGT** [comment]
Thanks for reporting this issue, it has been resolved in the latest version.

**Comment by HowCome** [comment]
Still in version: 13.2.0.0

**Comment by karthikveeraj** [comment]
This issue still exists on the NuGet package NSwag.ApiDescription.Client with the version 13.18.2
